name: TPARequestGUI
version: '1.2'
main: me.snowznz.tparequestgui.TPARequestGUI
author: SnowzNZ
description: A GUI for EssentialsX TPA requests
website: https://github.com/SnowzNZ/TPARequestGUI
api-version: '1.20'
depend:
  - Essentials
commands:
  tpagui:
    permission: tpagui.settings
    description: Manage the TPAGUI
    usage: "Usage: /<command> [enable|disable|reload]"
permissions:
  tpagui.settings:
    description: Allows you to use /tpagui
    default: true
  tpagui.reload:
    description: Allows you to reload the config with /tpagui reload
    default: op
